springdoc:
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html
  show-actuator: false

server:
  port: 8081

logging:
  level:
    org.springframework: debug

eureka:
  client:
    healthcheck:
      enabled: false
      
